# -*- coding: utf-8 -*-
"""
/***************************************************************************
 ReservoirCreator
                                 A QGIS plugin
 This plugin creates the inundation area of a dam (a line) that is placed on a water course.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2021-05-09
        copyright            : (C) 2021 by Faruk Gurbuz
        email                : gurbuz2561@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load ReservoirCreator class from file ReservoirCreator.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .reservoir_creator import ReservoirCreator
    return ReservoirCreator(iface)
